name: Test
on:
  workflow_dispatch:

jobs:
  calculate-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@v7.1.4

      - name: Run script
        env:
          ZOTERO_ID: ${{ secrets.ZOTERO_ID }}
          ZOTERO_KEY: ${{ secrets.ZOTERO_KEY }}
          SENDER: ${{ secrets.SENDER }}
          RECEIVER: ${{ secrets.RECEIVER }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          CUSTOM_CONFIG: ${{ vars.CUSTOM_CONFIG }}
        run: |
          export DEBUG=true
          if [ -n "$CUSTOM_CONFIG" ]; then
            printf "%b\n" "$CUSTOM_CONFIG" > config/custom.yaml
            echo "Using CUSTOM_CONFIG variable:"
          else
            echo "Using committed config/custom.yaml:"
          fi
          cat config/custom.yaml
          uv run src/zotero_arxiv_daily/main.py
